CC=gcc
CFLAGS=-O2 -Wall -Wextra -pthread
all: createThreads sequential parallel1 parallel2 parallel3
createThreads: createThreads.c
sequential: sequential.c
parallel1: parallel1.c
parallel2: parallel2.c
parallel3: parallel3.c
clean:
	rm -f createThreads sequential parallel1 parallel2 parallel3