createThreads: createThreads.c
	gcc -o2 -Wall -Wextra -pthread createThreads.c -o createThreads

parallel1: parallel1.c
	gcc -o2 -Wall -Wextra -pthread parallel1.c -o parallel1

parallel2: parallel2.c
	gcc -o2 -Wall -Wextra -pthread parallel2.c -o parallel2

parallel3: parallel3.c
	gcc -o2 -Wall -Wextra -pthread parallel3.c -o parallel3

sequential: sequential.c
	gcc -o2 -Wall -Wextra -pthread sequential.c -o sequential

